---
- name: "Install scl repo (CentOS)"
  yum:
    name: "centos-release-scl"
    state: "installed"
  when:
    - ansible_distribution == "CentOS"

- name: "Install scl repo (RedHat)"
  command: "yum-config-manager --enable rhel-server-rhscl-7-rpm"
  when:
    - ansible_distribution == "RedHat"

- name: "Enable SCL repo"
  ini_file:
    path: /etc/yum.repos.d/redhat.repo
    section: rhel-server-rhscl-7-rpms
    option: enabled
    value: 1
  when:
    - ansible_distribution == "RedHat"

- name: "Install memcached packages"
  package: "name=memcached state=latest"

- name: "Write memcached.conf"
  template: "src=memcached.conf.j2 dest=/etc/memcached.conf owner=root group=root mode=0644"
  notify:
    - "Restart memcached"
  when: ansible_os_family == "Debian"

- name: "Write sysconfig/memcached (RedHat)"
  template: "src=etc_sysconfig_memcached.j2 dest=/etc/sysconfig/memcached owner=root group=root mode=0644"
  notify:
    - "Restart memcached"
  when: ansible_os_family == "RedHat"

- name: "Set the max open file descriptors"
  sysctl: "name=fs.file-max value={{ memcached_fs_file_max }} state=present"

- name: "Start and enable the memcached service"
  service: "name=memcached state=started enabled=yes"
